// AUTOGENERATED — DO NOT EDIT.
// Source: src/lib/sdk-delegates/sdk-methods.ts
// Generator: scripts/sdk-codegen/emit-turbomodule-spec.ts
// Regenerate: pnpm sdk-codegen
// Last codegen commit: e77caa56c0afdb8ec33825cc98fd5d0941c4ca7f

import type { TurboModule } from 'react-native';
import { TurboModuleRegistry } from 'react-native';
import type { EventEmitter, UnsafeObject } from 'react-native/Libraries/Types/CodegenTypes';

/**
 * The native surface of @appdna-ai/react-native-sdk.
 *
 * A pure-Swift TurboModule is impossible: codegen emits a C++ `NativeAppdnaModuleSpecJSI` plus an
 * ObjC `@protocol`, and registration returns a `std::shared_ptr<facebook::react::TurboModule>`
 * over C++/JSI/folly headers Swift cannot import. `ios/AppdnaModule.mm` is the required ObjC++
 * adapter; it forwards to the Swift class through the generated `-Swift.h` header.
 */
export interface Spec extends TurboModule {
  /**
   * Configure the SDK. `framework` is injected by the native bridge and cannot be set by the
   * host.
   */
  configure(apiKey: string, env: string, options?: Object): Promise<void>;

  /** Identify the current user. */
  identify(userId: string, traits?: Object): Promise<void>;

  /** Clear identity and start a new anonymous session. */
  reset(): Promise<void>;

  /**
   * Track an event. Fire-and-forget: native enqueues, so a Promise per call would allocate for
   * nothing (W17).
   */
  track(event: string, properties?: Object): void;

  /** Force an immediate upload of queued events. */
  flush(): Promise<void>;

  /** Grant or revoke analytics consent. Persisted across cold start (AC-36). */
  setConsent(analytics: boolean): Promise<void>;

  /** Whether analytics consent is currently granted. No-arg — the docs' `{type}` was fiction. */
  isConsentGranted(): Promise<boolean>;

  /** Set log verbosity: none|error|warning|info|debug. */
  setLogLevel(level: string): void;

  /** Flush and tear down. The SDK must be re-configured before further use. */
  shutdown(): Promise<void>;

  /** The native core SDK version. */
  getSdkVersion(): Promise<string>;

  /** A human-readable diagnostic report. Includes the consent decision and veto-timeout count. */
  diagnose(): Promise<string>;

  /** The last non-fatal init error as `{type, message}`, or null. D-k. */
  getLastInitError(): Promise<string>;

  /**
   * Announce the visible screen. Populates `context.screen` on every subsequent event (D-h,
   * AC-22).
   */
  notifyScreenAppeared(screenName: string): void;

  /** Resolves once the SDK has finished bootstrapping. */
  onReady(): Promise<void>;

  /** A config value of unknown shape, JSON-encoded (E2). */
  getRemoteConfig(key: string): Promise<string>;

  /** Every config value, JSON-encoded. */
  getAllRemoteConfig(): Promise<string>;

  /** Force a config re-fetch, bypassing the TTL. */
  refreshConfig(): Promise<void>;

  /** Whether a boolean flag is on. */
  isFeatureEnabled(flag: string): Promise<boolean>;

  /** A flag's value of unknown shape, JSON-encoded (E2). */
  getFeatureVariant(flag: string): Promise<string>;

  /** The assigned variant id, or null. */
  getExperimentVariant(experimentId: string): Promise<string>;

  /** Whether the user is in a given variant. */
  isInVariant(experimentId: string, variantId: string): Promise<boolean>;

  /** An experiment config value, JSON-encoded (E2). */
  getExperimentConfig(experimentId: string, key: string): Promise<string>;

  /**
   * Recorded exposures as `{experimentId, variant}`. `Object[]`, never `UnsafeObject[]` — the
   * latter is a parse error.
   */
  getExperimentExposures(): Promise<Object[]>;

  /** Present an onboarding flow. Resolves false when no view controller / activity is available. */
  presentOnboarding(flowId: string, context?: Object): Promise<boolean>;

  /** Present a paywall by id. */
  presentPaywall(paywallId: string, context?: Object): Promise<void>;

  /**
   * Present the paywall configured for a placement (N17: an iOS overload, a distinct Android
   * name).
   */
  presentPaywallByPlacement(placement: string, context?: Object): Promise<void>;

  /** Present a survey by id. */
  presentSurvey(surveyId: string): Promise<void>;

  /**
   * Present a server-driven screen. Resolves false when no view controller / activity was
   * available to present from — the same contract as presentOnboarding. The RESULT arrives on
   * `onScreenDismissed`, not here: a screen can be dismissed long after the call resolves.
   */
  showScreen(screenId: string): Promise<boolean>;

  /**
   * Present a multi-screen flow. Resolves false when nothing could present it. The result
   * arrives on `onFlowCompleted`.
   */
  showFlow(flowId: string): Promise<boolean>;

  /** Dismiss the currently presented screen, if any. */
  dismissScreen(): Promise<void>;

  /**
   * Render a screen straight from a JSON payload, bypassing remote config. For console preview /
   * QA, not production.
   */
  previewScreen(json: string): Promise<boolean>;

  /**
   * Let the SDK inject server-driven screens into the host's navigation. Omit `screens` to
   * intercept all of them.
   */
  enableNavigationInterception(screens?: string[]): Promise<void>;

  /** Stop intercepting navigation. */
  disableNavigationInterception(): Promise<void>;

  /** Store a value for the current session. `valueJson` is JSON-encoded (E2). */
  setSessionData(key: string, valueJson: string): Promise<void>;

  /** A session value of unknown shape, JSON-encoded (E2). Null when unset. */
  getSessionData(key: string): Promise<string>;

  /** Drop every session value. */
  clearSessionData(): Promise<void>;

  /** The traits currently attached to the user, JSON-encoded (E2). */
  getUserTraits(): Promise<string>;

  /**
   * The structured location captured by an onboarding location field, JSON-encoded. Null when
   * that field was never answered.
   */
  getLocationData(fieldId: string): Promise<string>;

  /** Suppress in-app message display (e.g. during checkout). */
  suppressMessages(suppress: boolean): void;

  /** Buy a product. `offerToken` selects a Play offer and is ignored on iOS. */
  purchase(productId: string, offerToken?: string): Promise<Object>;

  /** Restored PRODUCT IDS — not entitlements. `[String]` / `List<String>` natively. */
  restorePurchases(): Promise<string[]>;

  /** Store product metadata. */
  getProducts(productIds: string[]): Promise<Object[]>;

  /** Whether any subscription entitlement is currently active. */
  hasActiveSubscription(): Promise<boolean>;

  /** Current entitlements. Shape is the reconciled union (N11). */
  getEntitlements(): Promise<Object[]>;

  /** Begin emitting `onEntitlementsChanged`. */
  startEntitlementObserver(): Promise<void>;

  /** Request the OS notification permission. */
  requestPushPermission(): Promise<boolean>;

  /** The current push token, or null. */
  getPushToken(): Promise<string>;

  /** Set the push token. Hex-encoded APNs data on iOS; the FCM string on Android (N9). */
  setPushToken(token: string): Promise<void>;

  /** Record the host's notification-permission state. */
  setPushPermission(granted: boolean): Promise<void>;

  /** Attribute a delivered push. */
  trackPushDelivered(pushId: string): Promise<void>;

  /** Attribute a tapped push. */
  trackPushTapped(pushId: string, action?: string): Promise<void>;

  /** Hand a deep link to the SDK (N15: `URL` on iOS, `String` on Android). */
  handleDeepLink(url: string): Promise<void>;

  /** The deferred deep link captured at install, or null. */
  checkDeferredDeepLink(): Promise<string>;

  /** The current web entitlement, or null. */
  getWebEntitlement(): Promise<string>;

  /**
   * Answer a pending native→JS veto. Native→JS is one-way, so the reply travels as an explicit
   * call (§5).
   */
  respondToHostCallback(callbackId: string, resultJson: string): void;

  // ── Events (native → JS, one-way) ─────────────────────────────────────────
  //
  // There is no reply channel here. A veto that needs an answer is delivered as `onHostCallback`
  // and answered with `respondToHostCallback(callbackId, resultJson)`. Native awaits FOREVER: the
  // 5-second timer lives in the wrapper's native code, never in a JS `setTimeout` (E5).

  /** A subsystem failed to start. Analytics keep running (D-k, AC-31). */
  readonly onInitDegraded: EventEmitter<UnsafeObject>;

  /** Remote config was refreshed. Native passes no args; the facade re-reads getAll(). */
  readonly onRemoteConfigChanged: EventEmitter<UnsafeObject>;

  /** Feature flags were refreshed. */
  readonly onFeatureFlagsChanged: EventEmitter<UnsafeObject>;

  readonly onOnboardingStarted: EventEmitter<UnsafeObject>;

  readonly onOnboardingStepChanged: EventEmitter<UnsafeObject>;

  readonly onOnboardingCompleted: EventEmitter<UnsafeObject>;

  readonly onOnboardingDismissed: EventEmitter<UnsafeObject>;

  /** Observe-only. Fires after an onboarding permission resolves, however it resolved. */
  readonly onPermissionResult: EventEmitter<UnsafeObject>;

  readonly onPaywallPresented: EventEmitter<UnsafeObject>;

  readonly onPaywallAction: EventEmitter<UnsafeObject>;

  readonly onPaywallPurchaseStarted: EventEmitter<UnsafeObject>;

  readonly onPaywallPurchaseCompleted: EventEmitter<UnsafeObject>;

  readonly onPaywallPurchaseFailed: EventEmitter<UnsafeObject>;

  readonly onPaywallDismissed: EventEmitter<UnsafeObject>;

  readonly onPaywallRestoreStarted: EventEmitter<UnsafeObject>;

  /** Payload is `{paywallId, restoredProductIds}`. */
  readonly onPaywallRestoreCompleted: EventEmitter<UnsafeObject>;

  readonly onPaywallRestoreFailed: EventEmitter<UnsafeObject>;

  /** The SDK asks the host to open a URL after a purchase. */
  readonly onPostPurchaseDeepLink: EventEmitter<UnsafeObject>;

  /** The SDK asks the host to continue to the next onboarding step. */
  readonly onPostPurchaseNextStep: EventEmitter<UnsafeObject>;

  readonly onPurchaseCompleted: EventEmitter<UnsafeObject>;

  readonly onPurchaseFailed: EventEmitter<UnsafeObject>;

  readonly onRestoreCompleted: EventEmitter<UnsafeObject>;

  readonly onEntitlementsChanged: EventEmitter<UnsafeObject>;

  /** Android-only: Play Billing is unavailable on this device (N8). */
  readonly onBillingUnavailable: EventEmitter<UnsafeObject>;

  /** A server-driven screen appeared. Payload `{screenId}`. */
  readonly onScreenPresented: EventEmitter<UnsafeObject>;

  /** A screen closed. Payload `{screenId, result}` — this is where a showScreen() result arrives. */
  readonly onScreenDismissed: EventEmitter<UnsafeObject>;

  /** A multi-screen flow finished. Payload `{flowId, result}`. */
  readonly onFlowCompleted: EventEmitter<UnsafeObject>;

  readonly onSurveyPresented: EventEmitter<UnsafeObject>;

  /**
   * Payload is `{surveyId, responses: [{questionId, answer}]}` — NOT Flutter's orphan
   * SurveyResult.
   */
  readonly onSurveyCompleted: EventEmitter<UnsafeObject>;

  readonly onSurveyDismissed: EventEmitter<UnsafeObject>;

  readonly onMessageShown: EventEmitter<UnsafeObject>;

  readonly onMessageAction: EventEmitter<UnsafeObject>;

  readonly onMessageDismissed: EventEmitter<UnsafeObject>;

  readonly onPushTokenRegistered: EventEmitter<UnsafeObject>;

  readonly onPushReceived: EventEmitter<UnsafeObject>;

  readonly onPushTapped: EventEmitter<UnsafeObject>;

  readonly onDeepLinkReceived: EventEmitter<UnsafeObject>;

  readonly onWebEntitlementChanged: EventEmitter<UnsafeObject>;

  /** SPEC-404: the backend locked this SDK key. Payload `{reason, lockedAt}`. */
  readonly onSdkRuntimeLocked: EventEmitter<UnsafeObject>;

  /** SPEC-404: the lock cleared. */
  readonly onSdkRuntimeUnlocked: EventEmitter<UnsafeObject>;

  /**
   * A native→JS veto request: `{callbackId, hook, argsJson}`. JS answers with
   * `respondToHostCallback`. Native awaits FOREVER — the 5s timer lives in the wrapper (§5).
   */
  readonly onHostCallback: EventEmitter<UnsafeObject>;
}

// `getEnforcing` throws when the module is absent. The facade never calls this directly — it goes
// through `src/nativeModule.ts`, which raises a directed error naming Expo Go, `pod install` and
// the unsupported runtimes instead of RN's bare `AppdnaModule is undefined` (D-q2).
export default TurboModuleRegistry.getEnforcing<Spec>('AppdnaModule');
