// AUTOGENERATED — DO NOT EDIT.
// Source: src/lib/sdk-delegates/sdk-methods.ts
// Generator: scripts/sdk-codegen/emit-turbomodule-ios-adapter.ts
// Regenerate: pnpm sdk-codegen
// Last codegen commit: ea81e45d0e1549af59d43b0f74403741833808fd

#import <React/RCTAssert.h>
#import <React/RCTBridgeModule.h>
#import <ReactCommon/RCTTurboModule.h>

#import "AppdnaEventSink.h"
#import "RNAppdnaSpec/RNAppdnaSpec.h"

// The pod is `appdna-sdk-react-native`; CocoaPods rewrites '-' to '_' for the module name, and
// `DEFINES_MODULE = YES` in the podspec is what makes this generated header exist.
#import <appdna_sdk_react_native/appdna_sdk_react_native-Swift.h>

/**
 * The AppDNA TurboModule.
 *
 * Subclasses `NativeAppdnaModuleSpecBase` (which owns the C++ EventEmitterCallback) and conforms to
 * `NativeAppdnaModuleSpec`. Every method forwards to `AppdnaModuleImpl`, the Swift class that
 * actually talks to AppDNASDK. See the emitter's header comment for why the split is not optional.
 */
@interface AppdnaModule : NativeAppdnaModuleSpecBase <NativeAppdnaModuleSpec, AppdnaEventSink>
@end

@implementation AppdnaModule {
  AppdnaModuleImpl *_impl;
}

RCT_EXPORT_MODULE()

- (instancetype)init
{
  if (self = [super init]) {
    _impl = [AppdnaModuleImpl new];
    _impl.eventSink = self;
  }
  return self;
}

/**
 * E10 / §2.3 — `requiresMainQueueSetup` is NO by native grace: the core SDK self-marshals onto the
 * main thread where it needs to (`AppDNA.swift:458,485,1342`). Recorded as a dependency, not an
 * assumption.
 */
+ (BOOL)requiresMainQueueSetup
{
  return NO;
}

- (void)invalidate
{
  [_impl invalidate];
  [super invalidate];
}

#pragma mark - Events (native → JS)

- (void)emitEventNamed:(NSString *)name payload:(NSDictionary *)payload
{
  if ([name isEqualToString:@"onInitDegraded"]) { [self emitOnInitDegraded:payload]; return; }
  if ([name isEqualToString:@"onRemoteConfigChanged"]) { [self emitOnRemoteConfigChanged:payload]; return; }
  if ([name isEqualToString:@"onFeatureFlagsChanged"]) { [self emitOnFeatureFlagsChanged:payload]; return; }
  if ([name isEqualToString:@"onOnboardingStarted"]) { [self emitOnOnboardingStarted:payload]; return; }
  if ([name isEqualToString:@"onOnboardingStepChanged"]) { [self emitOnOnboardingStepChanged:payload]; return; }
  if ([name isEqualToString:@"onOnboardingCompleted"]) { [self emitOnOnboardingCompleted:payload]; return; }
  if ([name isEqualToString:@"onOnboardingDismissed"]) { [self emitOnOnboardingDismissed:payload]; return; }
  if ([name isEqualToString:@"onPermissionResult"]) { [self emitOnPermissionResult:payload]; return; }
  if ([name isEqualToString:@"onPaywallPresented"]) { [self emitOnPaywallPresented:payload]; return; }
  if ([name isEqualToString:@"onPaywallAction"]) { [self emitOnPaywallAction:payload]; return; }
  if ([name isEqualToString:@"onPaywallPurchaseStarted"]) { [self emitOnPaywallPurchaseStarted:payload]; return; }
  if ([name isEqualToString:@"onPaywallPurchaseCompleted"]) { [self emitOnPaywallPurchaseCompleted:payload]; return; }
  if ([name isEqualToString:@"onPaywallPurchaseFailed"]) { [self emitOnPaywallPurchaseFailed:payload]; return; }
  if ([name isEqualToString:@"onPaywallDismissed"]) { [self emitOnPaywallDismissed:payload]; return; }
  if ([name isEqualToString:@"onPaywallRestoreStarted"]) { [self emitOnPaywallRestoreStarted:payload]; return; }
  if ([name isEqualToString:@"onPaywallRestoreCompleted"]) { [self emitOnPaywallRestoreCompleted:payload]; return; }
  if ([name isEqualToString:@"onPaywallRestoreFailed"]) { [self emitOnPaywallRestoreFailed:payload]; return; }
  if ([name isEqualToString:@"onPostPurchaseDeepLink"]) { [self emitOnPostPurchaseDeepLink:payload]; return; }
  if ([name isEqualToString:@"onPostPurchaseNextStep"]) { [self emitOnPostPurchaseNextStep:payload]; return; }
  if ([name isEqualToString:@"onPurchaseCompleted"]) { [self emitOnPurchaseCompleted:payload]; return; }
  if ([name isEqualToString:@"onPurchaseFailed"]) { [self emitOnPurchaseFailed:payload]; return; }
  if ([name isEqualToString:@"onRestoreCompleted"]) { [self emitOnRestoreCompleted:payload]; return; }
  if ([name isEqualToString:@"onEntitlementsChanged"]) { [self emitOnEntitlementsChanged:payload]; return; }
  if ([name isEqualToString:@"onBillingUnavailable"]) { [self emitOnBillingUnavailable:payload]; return; }
  if ([name isEqualToString:@"onSurveyPresented"]) { [self emitOnSurveyPresented:payload]; return; }
  if ([name isEqualToString:@"onSurveyCompleted"]) { [self emitOnSurveyCompleted:payload]; return; }
  if ([name isEqualToString:@"onSurveyDismissed"]) { [self emitOnSurveyDismissed:payload]; return; }
  if ([name isEqualToString:@"onMessageShown"]) { [self emitOnMessageShown:payload]; return; }
  if ([name isEqualToString:@"onMessageAction"]) { [self emitOnMessageAction:payload]; return; }
  if ([name isEqualToString:@"onMessageDismissed"]) { [self emitOnMessageDismissed:payload]; return; }
  if ([name isEqualToString:@"onPushTokenRegistered"]) { [self emitOnPushTokenRegistered:payload]; return; }
  if ([name isEqualToString:@"onPushReceived"]) { [self emitOnPushReceived:payload]; return; }
  if ([name isEqualToString:@"onPushTapped"]) { [self emitOnPushTapped:payload]; return; }
  if ([name isEqualToString:@"onDeepLinkReceived"]) { [self emitOnDeepLinkReceived:payload]; return; }
  if ([name isEqualToString:@"onWebEntitlementChanged"]) { [self emitOnWebEntitlementChanged:payload]; return; }
  if ([name isEqualToString:@"onSdkRuntimeLocked"]) { [self emitOnSdkRuntimeLocked:payload]; return; }
  if ([name isEqualToString:@"onSdkRuntimeUnlocked"]) { [self emitOnSdkRuntimeUnlocked:payload]; return; }
  if ([name isEqualToString:@"onHostCallback"]) { [self emitOnHostCallback:payload]; return; }

  // An event with no emitter is a programming error, not a runtime condition. Dropping it silently
  // is precisely the bug class this phase exists to kill — the old module's supportedEvents()
  // returned two names while ~30 JS listeners waited on emitters that did not exist.
  RCTAssert(NO, @"[AppDNA] no TurboModule emitter for event '%@'", name);
}

#pragma mark - Methods (JS → native)

- (void)configure:(NSString *)apiKey
            env:(NSString *)env
            options:(NSDictionary *)options
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl configure:apiKey env:env options:options resolve:resolve reject:reject];
}

- (void)identify:(NSString *)userId
            traits:(NSDictionary *)traits
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl identify:userId traits:traits resolve:resolve reject:reject];
}

- (void)reset:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl reset:resolve reject:reject];
}

- (void)track:(NSString *)event
            properties:(NSDictionary *)properties
{
  [_impl track:event properties:properties];
}

- (void)flush:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl flush:resolve reject:reject];
}

- (void)setConsent:(BOOL)analytics
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl setConsent:analytics resolve:resolve reject:reject];
}

- (void)isConsentGranted:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl isConsentGranted:resolve reject:reject];
}

- (void)setLogLevel:(NSString *)level
{
  [_impl setLogLevel:level];
}

- (void)shutdown:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl shutdown:resolve reject:reject];
}

- (void)getSdkVersion:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl getSdkVersion:resolve reject:reject];
}

- (void)diagnose:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl diagnose:resolve reject:reject];
}

- (void)getLastInitError:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl getLastInitError:resolve reject:reject];
}

- (void)notifyScreenAppeared:(NSString *)screenName
{
  [_impl notifyScreenAppeared:screenName];
}

- (void)onReady:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl onReady:resolve reject:reject];
}

- (void)getRemoteConfig:(NSString *)key
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl getRemoteConfig:key resolve:resolve reject:reject];
}

- (void)getAllRemoteConfig:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl getAllRemoteConfig:resolve reject:reject];
}

- (void)refreshConfig:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl refreshConfig:resolve reject:reject];
}

- (void)isFeatureEnabled:(NSString *)flag
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl isFeatureEnabled:flag resolve:resolve reject:reject];
}

- (void)getFeatureVariant:(NSString *)flag
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl getFeatureVariant:flag resolve:resolve reject:reject];
}

- (void)getExperimentVariant:(NSString *)experimentId
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl getExperimentVariant:experimentId resolve:resolve reject:reject];
}

- (void)isInVariant:(NSString *)experimentId
            variantId:(NSString *)variantId
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl isInVariant:experimentId variantId:variantId resolve:resolve reject:reject];
}

- (void)getExperimentConfig:(NSString *)experimentId
            key:(NSString *)key
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl getExperimentConfig:experimentId key:key resolve:resolve reject:reject];
}

- (void)getExperimentExposures:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl getExperimentExposures:resolve reject:reject];
}

- (void)presentOnboarding:(NSString *)flowId
            context:(NSDictionary *)context
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl presentOnboarding:flowId context:context resolve:resolve reject:reject];
}

- (void)presentPaywall:(NSString *)paywallId
            context:(NSDictionary *)context
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl presentPaywall:paywallId context:context resolve:resolve reject:reject];
}

- (void)presentPaywallByPlacement:(NSString *)placement
            context:(NSDictionary *)context
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl presentPaywallByPlacement:placement context:context resolve:resolve reject:reject];
}

- (void)presentSurvey:(NSString *)surveyId
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl presentSurvey:surveyId resolve:resolve reject:reject];
}

- (void)suppressMessages:(BOOL)suppress
{
  [_impl suppressMessages:suppress];
}

- (void)purchase:(NSString *)productId
            offerToken:(NSString *)offerToken
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl purchase:productId offerToken:offerToken resolve:resolve reject:reject];
}

- (void)restorePurchases:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl restorePurchases:resolve reject:reject];
}

- (void)getProducts:(NSArray *)productIds
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl getProducts:productIds resolve:resolve reject:reject];
}

- (void)hasActiveSubscription:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl hasActiveSubscription:resolve reject:reject];
}

- (void)getEntitlements:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl getEntitlements:resolve reject:reject];
}

- (void)startEntitlementObserver:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl startEntitlementObserver:resolve reject:reject];
}

- (void)requestPushPermission:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl requestPushPermission:resolve reject:reject];
}

- (void)getPushToken:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl getPushToken:resolve reject:reject];
}

- (void)setPushToken:(NSString *)token
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl setPushToken:token resolve:resolve reject:reject];
}

- (void)setPushPermission:(BOOL)granted
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl setPushPermission:granted resolve:resolve reject:reject];
}

- (void)trackPushDelivered:(NSString *)pushId
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl trackPushDelivered:pushId resolve:resolve reject:reject];
}

- (void)trackPushTapped:(NSString *)pushId
            action:(NSString *)action
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl trackPushTapped:pushId action:action resolve:resolve reject:reject];
}

- (void)handleDeepLink:(NSString *)url
            resolve:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl handleDeepLink:url resolve:resolve reject:reject];
}

- (void)checkDeferredDeepLink:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl checkDeferredDeepLink:resolve reject:reject];
}

- (void)getWebEntitlement:(RCTPromiseResolveBlock )resolve
            reject:(RCTPromiseRejectBlock )reject
{
  [_impl getWebEntitlement:resolve reject:reject];
}

- (void)respondToHostCallback:(NSString *)callbackId
            resultJson:(NSString *)resultJson
{
  [_impl respondToHostCallback:callbackId resultJson:resultJson];
}

#pragma mark - TurboModule registration

/// The one thing Swift genuinely cannot do: return a `std::shared_ptr` over JSI/folly headers.
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativeAppdnaModuleSpecJSI>(params);
}

@end
